#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index_admin:
    path: /Admin/
    controller: App\Areas\Admin\Controller\IndexController::index
app_login:
    path: /
    controller: App\Areas\User\Controller\ReceptionController::index
